services:
  fmd2:
    image: ablizno/fmd2:latest
    container_name: fmd2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK=022
      - THRESHOLD_MINUTES=3
      - TRANSFER_FILE_TYPE=.cbz
    ports:
      - 3000:3000
    volumes:
      - /path/to/appdata:/app/FMD2/userdata
      - /path/to/manga:/downloads
    restart: unless-stopped
